use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'CwgDemoTest_Example' do
  pod 'CwgDemoTest', :path => '../'

  target 'CwgDemoTest_Tests' do
    inherit! :search_paths

    
  end
end
